baseURL = "https://gwuspain.org/"
languageCode = "es-es"
title = "GWU Espa침a"
theme = "gwuspain"

disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
  home     = ["HTML"]
  section  = ["HTML", "RSS"]

[params]
    description = "Divisi칩n espa침ola de la organizaci칩n Game Workers Unite."

    inscriptionUrl = "https://goo.gl/forms/C8Ji3rrsvloYXiIx2"
    contactEmail = "contact@gwuspain.org"
    twitterSpain = "GWU_Spain"
    twitterInternational = "GameWorkers"
